main: xyz.prorickey.kitx.KitX
author: Prorickey
version: 1.2.0-beta
name: KitX

commands:
  kitx:
    usage: /kitx <subcommand>
    description: To edit and use kits
  kit:
    usage: /kit <kitname>
    description: To get a kit